GET http://localhost:8080/transaction/company/get_debit_by_cardId/8a8a8394822ac4b901822ac59e1b0004
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1NzQ5NDYsImV4cCI6MTY1ODc5MDk0NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiMTc4MjI3OTI2OTAxODIyNzkyNzExNTAwMDIiLCJyb2xlIjoiUk9MRV9CQU5LIn0.CoOYnEUyWMSqsam8s2nAXTTqaxcLiLcSAJ6A3r0O110

###
GET localhost:8080/transaction/company/get_last_month/8600378380316296
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg1NzQ5NDYsImV4cCI6MTY1ODc5MDk0NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiNDAyOGFiMTc4MjI3OTI2OTAxODIyNzkyNzExNTAwMDIiLCJyb2xlIjoiUk9MRV9CQU5LIn0.CoOYnEUyWMSqsam8s2nAXTTqaxcLiLcSAJ6A3r0O110
